package fsadapter

import (
	"io"
	"os"
	"path/filepath"
)

func AtomicWriteFile(fullPath string, perm os.FileMode, r io.Reader) error {
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o750); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(fullPath), ".tmp-*")
	if err != nil {
		return err
	}
	defer func() { _ = os.Remove(tmp.Name()) }() // #nosec G703 -- tmp path is generated by os.CreateTemp
	if _, err := io.Copy(tmp, r); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), fullPath) // #nosec G703 -- tmp path is generated by os.CreateTemp
}
