FROM golang:1.25-alpine

RUN apk add --no-cache bash curl unzip git protoc

ENV PATH=$PATH:/root/go/bin

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.29.0
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.16.0

WORKDIR /work
COPY . /work
CMD ["make", "proto"]