package local

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"io"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/example/file-engine/internal/storage"
)

type LocalStorage struct {
	base string
}

func New(base string) *LocalStorage {
	return &LocalStorage{base: base}
}

func (l *LocalStorage) full(p string) string {
	clean := normalizePath(p)
	joined := filepath.Join(l.base, clean)

	// Ensure that the resolved path stays within the configured base directory.
	baseAbs, errBase := filepath.Abs(l.base)
	fullAbs, errFull := filepath.Abs(joined)
	if errBase != nil || errFull != nil {
		return l.base
	}

	baseWithSep := baseAbs
	if !strings.HasSuffix(baseWithSep, string(filepath.Separator)) {
		baseWithSep += string(filepath.Separator)
	}

	if fullAbs == baseAbs || strings.HasPrefix(fullAbs, baseWithSep) {
		return fullAbs
	}

	// If the path would escape the base directory, fall back to the base itself.
	return baseAbs
}

func normalizePath(p string) string {
	p = path.Clean("/" + path.Clean(strings.ReplaceAll(strings.TrimSpace(p), "\\", "/")))
	if p == "." {
		return "/"
	}
	return p
}

func (l *LocalStorage) CreateFolder(_ context.Context, path string) error {
	return os.MkdirAll(l.full(path), 0o750)
}

func (l *LocalStorage) AtomicWrite(_ context.Context, path string, r io.Reader) error {
	full := l.full(path)
	dir := filepath.Dir(full)
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, ".tmp-*")
	if err != nil {
		return err
	}
	if _, err := io.Copy(tmp, r); err != nil {
		_ = tmp.Close()
		return err
	}
	_ = tmp.Close()
	return os.Rename(tmp.Name(), full) // #nosec G703 -- tmp path is generated by os.CreateTemp
}

func (l *LocalStorage) Move(_ context.Context, src, dst string) error {
	srcF := l.full(src)
	dstF := l.full(dst)
	if err := os.MkdirAll(filepath.Dir(dstF), 0o750); err != nil {
		return err
	}
	if err := os.Rename(srcF, dstF); err == nil {
		return nil
	}
	// fallback copy+delete
	in, err := os.Open(srcF) // #nosec G304 -- srcF is normalized by l.full
	if err != nil {
		return err
	}
	defer func() { _ = in.Close() }()
	out, err := os.Create(dstF) // #nosec G304 -- dstF is normalized by l.full
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		_ = out.Close()
		return err
	}
	_ = out.Close()
	return os.Remove(srcF)
}

func (l *LocalStorage) Delete(_ context.Context, path string) error {
	return os.RemoveAll(l.full(path))
}

func (l *LocalStorage) Exists(_ context.Context, path string) (bool, error) {
	_, err := os.Stat(l.full(path))
	if err == nil {
		return true, nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}
	return false, err
}

func (l *LocalStorage) List(_ context.Context, prefix string) ([]storage.ObjectInfo, error) {
	full := l.full(prefix)
	entries, err := os.ReadDir(full)
	if err != nil {
		return nil, err
	}
	out := make([]storage.ObjectInfo, 0, len(entries))
	for _, e := range entries {
		info, _ := e.Info()
		var size int64
		var modifiedAt time.Time
		var createdAt time.Time
		var owner string
		var group string
		if info != nil {
			size = info.Size()
			modifiedAt = info.ModTime()
			createdAt = modifiedAt
			if stat, ok := info.Sys().(*syscall.Stat_t); ok {
				owner = strconv.FormatUint(uint64(stat.Uid), 10)
				group = strconv.FormatUint(uint64(stat.Gid), 10)
			}
		}
		checksum := ""
		if info != nil && !e.IsDir() {
			if f, openErr := os.Open(l.full(filepath.Join(prefix, e.Name()))); openErr == nil {
				h := sha256.New()
				_, _ = io.Copy(h, f)
				checksum = hex.EncodeToString(h.Sum(nil))
				_ = f.Close()
			}
		}
		out = append(out, storage.ObjectInfo{
			Path:       filepath.Join(prefix, e.Name()),
			Size:       size,
			IsDir:      e.IsDir(),
			ModifiedAt: modifiedAt,
			CreatedAt:  createdAt,
			Owner:      owner,
			Group:      group,
			Checksum:   checksum,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

func (l *LocalStorage) Open(_ context.Context, path string) (io.ReadCloser, error) {
	return os.Open(l.full(path))
}
