#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
cd "$ROOT_DIR"

python - <<'PY'
import json, re
from pathlib import Path

root = Path('.')
server = (root / 'file-engine/internal/server/server.go').read_text()
proto = (root / 'file-engine/api/proto/fileengine.proto').read_text()

http_routes = sorted(set(re.findall(r'HandleFunc\("([^"]+)"', server)))
proto_routes = []
for m in re.finditer(r'(post|get):\s*"([^"]+)"', proto):
    proto_routes.append((m.group(1).upper(), m.group(2)))

# 1) Endpoint inventory
endpoint_out = root / 'docs/generated/endpoint-inventory.md'
endpoint_lines = [
    '# Generated Endpoint Inventory',
    '',
    'Auto-generated by `./scripts/generate-doc-artifacts.sh`. Do not edit manually.',
    '',
    '## HTTP routes registered in `file-engine/internal/server/server.go`',
    '',
    '| Route |',
    '| :-- |',
]
for route in http_routes:
    endpoint_lines.append(f'| `{route}` |')
endpoint_lines += ['', '## gRPC-Gateway proto HTTP bindings', '', '| Method | Route |', '| :-- | :-- |']
for method, route in proto_routes:
    endpoint_lines.append(f'| `{method}` | `{route}` |')
endpoint_out.write_text('\n'.join(endpoint_lines) + '\n')

# 2) Route maturity inventory
matrix_out = root / 'docs/generated/route-maturity-matrix.md'
base_routes = [r for r in http_routes if r.startswith('/v1/') or r in ['/readyz', '/metrics', '/healthz']]
for _, pr in proto_routes:
    if pr not in base_routes:
        base_routes.append(pr)
base_routes = sorted(base_routes)
matrix_lines = [
    '# Generated Route Maturity Matrix (Inventory)',
    '',
    'Auto-generated by `./scripts/generate-doc-artifacts.sh` from route registration and proto bindings.',
    '',
    '| Route | Source |',
    '| :-- | :-- |',
]
for route in base_routes:
    in_proto = any(pr == route for _, pr in proto_routes)
    in_server = route in http_routes
    source = 'server.go + proto' if in_proto and in_server else ('proto' if in_proto else 'server.go')
    matrix_lines.append(f'| `{route}` | {source} |')
matrix_out.write_text('\n'.join(matrix_lines) + '\n')

# 3) Dashboard references
dash_refs_out = root / 'docs/generated/dashboard-references.md'
dash_dir = root / 'monitoring/dashboards'
dash_lines = [
    '# Generated Dashboard References',
    '',
    'Auto-generated by `./scripts/generate-doc-artifacts.sh`.',
    '',
    '| Dashboard file | Title |',
    '| :-- | :-- |',
]
for p in sorted(dash_dir.glob('*.json')):
    title = p.stem
    try:
        title = json.loads(p.read_text()).get('title') or title
    except Exception:
        pass
    dash_lines.append(f'| `{p.as_posix()}` | {title} |')
dash_refs_out.write_text('\n'.join(dash_lines) + '\n')

# 4) SDK examples inventory (generated)
sdk_out = root / 'docs/generated/sdk-examples.md'
go_example = root / 'file-engine/examples/client/go_http_example.go'
php_client = root / 'backend/app/Clients/FileEngineClient.php'
sdk_lines = [
    '# Generated SDK Examples Inventory',
    '',
    'Auto-generated by `./scripts/generate-doc-artifacts.sh`. Do not edit manually.',
    '',
    '| SDK surface | File | Notes |',
    '| :-- | :-- | :-- |',
    f'| Go HTTP example | `{go_example.as_posix()}` | Example request lifecycle for thin client usage. |',
    f'| PHP engine client | `{php_client.as_posix()}` | Control-plane wrapper and typed error contract. |',
    '',
    '## Highlighted snippets',
    '',
]
if go_example.exists():
    sdk_lines += ['### Go: `main` in HTTP example', '```go']
    go_lines = go_example.read_text().splitlines()
    start = next((i for i, line in enumerate(go_lines) if line.strip().startswith('func main(')), 0)
    sdk_lines += go_lines[start:start+30]
    sdk_lines += ['```', '']
if php_client.exists():
    sdk_lines += ['### PHP: retry-aware request helper signatures', '```php']
    php_lines = php_client.read_text().splitlines()
    include = [line for line in php_lines if 'function postOrThrow' in line or 'function getOrThrow' in line or 'function putRawOrThrow' in line]
    sdk_lines += include[:6] or php_lines[:20]
    sdk_lines += ['```']
sdk_out.write_text('\n'.join(sdk_lines) + '\n')

# 5) Governance policy schema documentation (generated)
policy_out = root / 'docs/generated/policy-schema.md'
policy_example_path = root / 'file-engine/config/governance-policy.example.json'
policy = json.loads(policy_example_path.read_text())

def type_of(value):
    if isinstance(value, bool):
        return 'boolean'
    if isinstance(value, int):
        return 'integer'
    if isinstance(value, float):
        return 'number'
    if isinstance(value, list):
        return 'array'
    if isinstance(value, dict):
        return 'object'
    if value is None:
        return 'null'
    return 'string'

rows = []
def walk(node, path):
    if isinstance(node, dict):
        for key, val in node.items():
            next_path = f'{path}.{key}' if path else key
            rows.append((next_path, type_of(val), json.dumps(val) if not isinstance(val, (dict, list)) else 'see nested fields'))
            walk(val, next_path)
    elif isinstance(node, list) and node:
        sample = node[0]
        rows.append((f'{path}[]', type_of(sample), json.dumps(sample) if not isinstance(sample, (dict, list)) else 'see nested fields'))
        walk(sample, f'{path}[]')

walk(policy, '')
policy_lines = [
    '# Generated Governance Policy Schema (from example)',
    '',
    'Auto-generated by `./scripts/generate-doc-artifacts.sh` from `file-engine/config/governance-policy.example.json`.',
    '',
    '| Field path | Type | Example/default |',
    '| :-- | :-- | :-- |',
]
for field, typ, ex in rows:
    policy_lines.append(f'| `{field}` | `{typ}` | `{ex}` |')
policy_out.write_text('\n'.join(policy_lines) + '\n')
PY

echo "DOC_ARTIFACTS_GENERATED"
