#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
cd "$ROOT_DIR"

python - <<'PY'
import json, re
from pathlib import Path
root=Path('.')
server=(root/'file-engine/internal/server/server.go').read_text()
proto=(root/'file-engine/api/proto/fileengine.proto').read_text()

http_routes=sorted(set(re.findall(r'HandleFunc\("([^"]+)"', server)))
proto_routes=[]
for m in re.finditer(r'(post|get):\s*"([^"]+)"', proto):
    proto_routes.append((m.group(1).upper(), m.group(2)))

out=root/'docs/generated/endpoint-inventory.md'
lines=[
"# Generated Endpoint Inventory",
"",
"Auto-generated by `./scripts/generate-doc-artifacts.sh`. Do not edit manually.",
"",
"## HTTP routes registered in `file-engine/internal/server/server.go`",
"",
"| Route |",
"| :-- |",
]
for r in http_routes:
    lines.append(f"| `{r}` |")
lines += ["", "## gRPC-Gateway proto HTTP bindings", "", "| Method | Route |", "| :-- | :-- |"]
for m,r in proto_routes:
    lines.append(f"| `{m}` | `{r}` |")
out.write_text("\n".join(lines)+"\n")

matrix=root/'docs/generated/route-maturity-matrix.md'
base_routes=[r for r in http_routes if r.startswith('/v1/') or r in ['/readyz','/metrics','/healthz']]
for _,pr in proto_routes:
    if pr not in base_routes:
        base_routes.append(pr)
base_routes=sorted(base_routes)
m=[
"# Generated Route Maturity Matrix (Inventory)",
"",
"Auto-generated by `./scripts/generate-doc-artifacts.sh` from route registration and proto bindings.",
"",
"| Route | Source |", "| :-- | :-- |",
]
for r in base_routes:
    src='server.go'
    in_proto=any(pr==r for _,pr in proto_routes)
    in_server=r in http_routes
    if in_proto and in_server:
        src='server.go + proto'
    elif in_proto:
        src='proto'
    m.append(f"| `{r}` | {src} |")
matrix.write_text("\n".join(m)+"\n")

refs=root/'docs/generated/dashboard-references.md'
dash_dir=root/'monitoring/dashboards'
a=[
"# Generated Dashboard References",
"",
"Auto-generated by `./scripts/generate-doc-artifacts.sh`.",
"",
"| Dashboard file | Title |", "| :-- | :-- |",
]
for p in sorted(dash_dir.glob('*.json')):
    title=p.stem
    try:
        data=json.loads(p.read_text())
        title=data.get('title') or title
    except Exception:
        pass
    a.append(f"| `{p.as_posix()}` | {title} |")
refs.write_text("\n".join(a)+"\n")
PY

echo "DOC_ARTIFACTS_GENERATED"
