name: Semantic PR Check

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  title-check:
    runs-on: ubuntu-24.04
    outputs:
      type: ${{ steps.semantic-pr-check.outputs.type }}
    steps:
      - name: Check PR Title's semantic conformance
        id: semantic-pr-check
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
